### ISSUE TITLE
Out of source deployment

### ISSUE THREAD

**Issue by ObaniGemini** [LibreGameArchive/freetumble#10]
It would be preferable to have a new pathfinding system to reach the media files when launching the game.
Actually it can only be launched in its own folder.

**Comment by akien-mga** [comment]
Indeed, that's one of the block issues for 1.1 as I can't package it properly right now.

**Comment by ObaniGemini** [comment]
Would it be possible to do something like `*/freetumble/src/...` ?

**Comment by akien-mga** [comment]
I'm not sure what you mean, but typically the source code should check for data files next to the binary, and if it does not find them (i.e. the binary was installed somewhere, e.g. `/usr/games`) then it should look for the data in an appropriate folder (typically `/usr/share/games/freetumble`, but this would likely be made configurable at build time).

**Comment by akien-mga** [comment]
Closed by deb5c15.
